shell.run("wget https://raw.githubusercontent.com/cherrysrc/CC/main/storageSearcher/master/nodes.lua customAPI/nodes.lua")
shell.run("wget https://raw.githubusercontent.com/cherrysrc/CC/main/storageSearcher/master/screen customAPI/screen.lua")
shell.run("wget https://raw.githubusercontent.com/cherrysrc/CC/main/storageSearcher/master/find.lua find.lua")
shell.run("wget https://raw.githubusercontent.com/cherrysrc/CC/main/storageSearcher/master/register.lua register.lua")
shell.run("wget https://raw.githubusercontent.com/cherrysrc/CC/main/storageSearcher/master/storage.lua storage.lua")
shell.run("wget https://raw.githubusercontent.com/cherrysrc/CC/main/storageSearcher/master/unregister.lua unregister.lua")
